platform :ios, '8.0'
target 'AnLanBB' do
pod "MJRefresh"
pod 'AFNetworking'
pod 'SDWebImage'
pod "SVProgressHUD"
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'SwipeBack'

pod 'UMCCommon'
pod 'UMCCommonLog'
pod 'UMCPush'

pod 'ReactiveObjC'
pod 'TZImagePickerController'
pod 'Masonry'
end
